### ISSUE TITLE
Can't open FAE after updating

### ISSUE THREAD

**Issue by ashyashton** [AlexanDDOS/fae-mod#124]
[traceback.txt](https://github.com/ForeverAndEverTeam/fae-mod/files/11801844/traceback.txt)

Any help is appreciated!

**Comment by ashyashton** [comment]
Should I backup the "saves" folder first? There seems to be a persistent file there, but it does seem to be an old one.

**Comment by TRIDENT1313** [comment]
It won't matter.
Persistents are stored elsewhere aside from saves

**Comment by ashyashton** [comment]
It worked, thank you so much!!

**Comment by TRIDENT1313** [comment]
No problem!
