### ISSUE TITLE
[ Question ] Looking to ( Maybe ) Contribute. 🖌️🎨

### ISSUE THREAD

**Issue by Professor-JMO** [AlexanDDOS/fae-mod#16]
Hiya, I'm one of the community artists for MAS. <- I'm sure you've heard of it.
> I'm going around to each of the [ 4 ] `After Story` mods looking for excuses to contribute.
>> I'm afraid art is the best I can do for now, b u t it's all free! ( And relatively small for now. )

If this sounds like anything of minor interest even, we can work out the details later.
> `Just Yuri` passed me up on the offer and I will be coming into contact with the `just Natsuki` devs as well.

**Comment by AlexanDDOS** [comment]
I was looking for an artist since I'd started work on this project, so I'm glad you want to work for it. Can you give me your contact info for further communication? At least, you can send me e-mails at first.

**Comment by Saiv46** [comment]
Umm, hello?

**Comment by Professor-JMO** [comment]
@AlexanDDOS 
Sorry it's been a while! ( 5 months to be exact ) 💦 
B u t
I'm _ready_ to take up art for this project ☝️ 
Nothing "overhaul" worthy but additions and/or edits here and there.

Since my proposition many months ago I've since developed and applied myself a bit.
Currently I'm...
>A `Contributor` and `Ex-Community Artist` for `Monika After Story`.
>A 'Dev' for the `Just Yuri` Dev team.
>A `Artist/Editor` for `Just Natsuki` as well.

You can check my info my more closely and to verify via my Deviant profile: https://www.deviantart.com/professor-jmo

F&E is last on my list of mods I desire to contribute to and I'm sorry it's taken mi this long to settle. 🙏

**Comment by AlexanDDOS** [comment]
I'm glad you're finally ready to contribute my project. I'm looking for good collaboration.
I'm planing to add some customization for Sayori, so I'll need your help. I'll notice you when I need it.

**Comment by Professor-JMO** [comment]
Sounds good.

Got a Discord?

**Comment by Professor-JMO** [comment]
Just thought I'd check in, @AlexanDDOS 

Wanted to let you know I'm available whenever to begin work on any sprites as I've just finished up designing a `Base` for _Just Natsuki_.

You can find mi on discord or email mi even- though I think your last one ended up in my spam folder for some reason. 🤔

**Comment by AlexanDDOS** [comment]
Oops! Sorry for the silence. We can use Discord, of course.  My nickname is AlexanDDOS#5109.

**Comment by AlexanDDOS** [comment]
Thanks, @Orcaramelo. I'm glad you suggest your help too. Together, we can finally give some new features, requiring new image assets.
