### ISSUE TITLE
[Contribution] Spanish Translation

### ISSUE THREAD

**Issue by ElReyZero1201** [AlexanDDOS/fae-mod#18]
Hi, I'm a Spanish native speaker and would like to see this mod translated into Spanish. If you need someone, I can help to translate it. I've done translations before so I'm quite experienced in the subject.

**Comment by AlexanDDOS** [comment]
Thanks for your suggestion! I'll notice you when text is ready to be translated into the brand-new language.

**Comment by ElReyZero1201** [comment]
Sure, no problem. I'll gladly wait.

**Comment by AlexanDDOS** [comment]
@ElReyZero1201 
It's time to do, my amigo!

**Comment by ElReyZero1201** [comment]
Ok sure, DM me with the translation details.

**Comment by ElReyZero1201** [comment]
My email is juan.romero1201@gmail.com just in case you need it.

**Comment by ElReyZero1201** [comment]
What does self-voicing and clipboard voicing mean?

**Comment by AlexanDDOS** [comment]
Self-voicing is reading character lines with a text-to-speech program.  
Clipboard voicing a self-voicing test with a text from the clipboard as an example.

**Comment by ElReyZero1201** [comment]
Oh ok, thanks. I've already started translating. I'm 50% done with it.

**Comment by ElReyZero1201** [comment]
I have translated every file aside from topics.rpy which is 30.36% done. Should I start sending them to you? Or should I wait until I finish topics.rpy

**Comment by AlexanDDOS** [comment]
I think, you should finish the work before sending. I'm not planning to add new topics to the next update anyway.  
However, I'm planning to change the update message (that's included in topics.rpy) and recode Checkers, so can you translate new keys after I push commits with these changes?

**Comment by ElReyZero1201** [comment]
Sure, I'll finish topics.rpy and submit it to you. 

If you want, I can provide support for Spanish translation for this mod meaning I'll translate every new update and fix any typos.

**Comment by AlexanDDOS** [comment]
Thanks, man!

**Comment by ElReyZero1201** [comment]
I have finished translating the mod, where should I submit the files to you? I cannot create a pull request because this is a new feature. Should I email them to you?

**Comment by AlexanDDOS** [comment]
Yes, you should. I'm looking forward for your e-mail.

**Comment by ElReyZero1201** [comment]
Ok. I've already sent it to you. Let me know if there's anything else needed.

**Comment by ElReyZero1201** [comment]
Did you receive the files?

**Comment by AlexanDDOS** [comment]
Yes! I'll add them to the repo later.

**Comment by AlexanDDOS** [comment]
Hey! You missed some strings in 3 files. Can you fix them when I publish your translation?

**Comment by ElReyZero1201** [comment]
Yeah, sure. Just tell me which and I'll fix them asap.

**Comment by ElReyZero1201** [comment]
Will the update to the repo take time? Because I can fix the strings now, just tell me which, I'll correct them and send them back to you.

**Comment by AlexanDDOS** [comment]
Sorry for a delay! I just was too busy to upload your translation. Now you can commit your changes right to the mod repo.   
And please, can you translate all the poems from `poems.rpy`? It's needed to complete the translation, but you may leave them untranslated for the coming update, if you can't.

**Comment by ElReyZero1201** [comment]
Which lines? I've checked and I have everything translated

**Comment by ElReyZero1201** [comment]
Also, where should I commit the changes? I don't see any spanish folder in order to do it.

**Comment by ElReyZero1201** [comment]
Ok, I see where now

**Comment by ElReyZero1201** [comment]
I see that the language shortcut that you used for spanish was "esp", and I had it labeled as "es". I see that the files have my first translations labeled as es, but the new parts as esp. Should I change it to es? or are you gonna keep it as esp? if you keep it as esp, you would have to replace each string that has "es" manually because if you try to replace them all at once using the find and replace, you will replace also the word es in spanish, which means is or it's.

**Comment by ElReyZero1201** [comment]
Oh, I see now. The files are already translated. The translated strings are above of what you added. They are the same ones, as the ones below.

**Comment by ElReyZero1201** [comment]
I created a pull request now.

**Comment by ElReyZero1201** [comment]
Ok, I see what's happening right now. Can you change the Spanish shortcut from esp to es? Everything translated has the es shortcut, if I had to change it to esp, I would need to do all strings manually, and there are a lot of them.

**Comment by ElReyZero1201** [comment]
Ok, I see what's happening right now. Can you change the Spanish shortcut from esp to es? Everything translated has the es shortcut, if I had to change it to esp, I would need to do all strings manually, and there are a lot of them.

**Comment by ElReyZero1201** [comment]
Wait, I think I figured it out

**Comment by ElReyZero1201** [comment]
It worked! I'll commit to master now
