### ISSUE TITLE
The chibi doki discussion doesn't really work because the chibis and function to hide them are undefined.

### ISSUE THREAD

**Issue by TriniTDM** [AlexanDDOS/fae-mod#34]
This happens with all of them.
![Screenshot (2992)](https://user-images.githubusercontent.com/52469676/68170818-39d82580-ff3f-11e9-8f03-be2243d8360a.png)
![Screenshot (2993)](https://user-images.githubusercontent.com/52469676/68170848-57a58a80-ff3f-11e9-9919-3afbbed742c4.png)
But Sayori acts like nothing's going wrong.
![screenshot0002](https://user-images.githubusercontent.com/52469676/68170893-86bbfc00-ff3f-11e9-8ba7-275d420294ec.png)

**Comment by AlexanDDOS** [comment]
Sorry for the delayed answer. I seem to accidentally remove the transformations from the code. I need some time to restore them.
