### ISSUE TITLE
Concerning the "face" topic...

### ISSUE THREAD

**Issue by MonikaEndDie** [AlexanDDOS/fae-mod#36]
So basically, Sayori ask the player (us) if he has a photos of him in his computer. But if we say yes, how it work, then? She tell to put the photos in the game root folder (the main one i think), which i did... with 4 differents format (pdf, png, jpg and bmp), but she's still stuck in a no ending search loop and i have to quit without saying goodbye. I hate to do it! Is there a specific kind of format to use or do i need to put the photos in a different folder? Thanks for replying.

And just another quick question: are you planning to add a "i love you" button? It would be nice to expresse our love to Sayori like with Monika and Yuri.

**Comment by AlexanDDOS** [comment]
I can fix this issue and limit the expecting with a timer (like, Sayori will think you can't find any photo of you, so she won't bother you about this).  
What's about the "I love you" option, I though it's kinda useless feature, but I did even not know it comes from MAS and JY, as I hadn't follow them for the long time. Maybe, I'll add it to the coming update as well.

**Comment by MonikaEndDie** [comment]
Great! And even if it doesn't have a specific effect, it's still sweet to be affectionnate with our bubbly ray of sunshine like with others (even if just natsuki mod hasn't this feature yet for now). I'm waiting (im)patiently for this feature to come. Keep up the good work, pal.

**Comment by AlexanDDOS** [comment]
All of your requests are done. Thanks for your suggestions!

**Comment by ElReyZero1201** [comment]
Concerning the Photo topic, I tried it today and it isn't working. What folder are we supposed to paste the photo in? I tried the main game folder and \Doki Doki Literature Club\game.
The files I used were .jpg
