### ISSUE TITLE
[Menu] Long strings overlap with other strings when translated 

### ISSUE THREAD

**Issue by ElReyZero1201** [AlexanDDOS/fae-mod#39]
So I'm translating some of the new features and noticed that some long menu strings are overlapping with the strings above them.
![imagen](https://user-images.githubusercontent.com/31524106/78055027-8f76f980-7348-11ea-87d5-4249f6cda47a.png)

![imagen](https://user-images.githubusercontent.com/31524106/78055152-b6cdc680-7348-11ea-808c-5fea342524b2.png)
The strings in question are: "Pantalla Completa" (which stands for fullscreen), "Cambio Progresivo" (smooth) and "Apagado (Siempre de día)" (which is "Off (Always day)).

PS: I'm polishing the translations to sound more natural. So expect an update on that front.

**Comment by AlexanDDOS** [comment]
That's because the label size is strictly limited by the original game code. Either I'll remove this limit or you'll have to cut your strings to follow it. Wait for further messages in this issue.

**Comment by ElReyZero1201** [comment]
Ok, we can try removing the limit or increasing it if possible, and seeing how it turns out. Because there are some strings such as "Pantalla Completa" that cannot be changed to have fewer characters without altering its meaning. I'll be looking for some alternatives just in case.

**Comment by AlexanDDOS** [comment]
No, you don't have to do it now. I've fixed this issue already.

**Comment by ElReyZero1201** [comment]
Oh, nice! Thanks.
