### ISSUE TITLE
MC eating cookies uses old artwork.

### ISSUE THREAD

**Issue by ElReyZero** [AlexanDDOS/fae-mod#41]
When Sayori brings up the cookies topic and she asks if you want her to feed MC, if you say yes, the old artwork is used, then after a couple lines of dialogue, it turns back into the new artwork.

**Comment by AlexanDDOS** [comment]
It is a temporal issue that will be fixed by the release of the coming update. But anyway, thanks for the mention. This issue will be closed right when I fix it.

**Comment by AlexanDDOS** [comment]
Fixed!
