### ISSUE TITLE
[Question] What does "Rollback Side" do?

### ISSUE THREAD

**Issue by ElReyZero1201** [AlexanDDOS/fae-mod#43]
I was playing through the mod and noticed the "Rollback Side" option in settings, but I really don't know what it means. I translated it, but it doesn't really make sense. I tried turning it on, tried both sides (left and right), but it didn't make any noticeable changes (or I'm somewhat blind and didn't see them). What does it do? So that I can translate it properly.

**Comment by ElReyZero1201** [comment]
@AlexanDDOS I figured what Rollback Side was. I thought it was a feature of the mod, but it turns out it's from Ren'Py. I'll make a pull request sometime later with more correcrtions including that one.

**Comment by AlexanDDOS** [comment]
Honestly, I dunno with does it do myself. It should somehow change the rollback feature, but I don't know why this menu was left if the feature was disabled?

**Comment by ElReyZero1201** [comment]
Well, according to what I found in the Ren'Py documentation, when you enable it and let's say you select left, if you click on the left side of the screen, the dialogue goes back once. I've never had it enabled so I never knew what it did.
